# Generated by Django 5.1.2 on 2024-10-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Назва', models.CharField(max_length=255)),
                ('Опис', models.TextField()),
                ('Статус', models.CharField(choices=[], default='not_started', max_length=20)),
                ('Пріорітет', models.CharField(choices=[], default='medium', max_length=10)),
                ('Термін виконання', models.DateTimeField(blank=True, null=True)),
                ('Користувач', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
