# Generated by Django 5.1.2 on 2024-10-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_alter_task_пріорітет_alter_task_статус'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Термін виконання',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Опис',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Пріорітет',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Статус',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Назва',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Користувач',
            new_name='user',
        ),
    ]
