# Generated by Django 5.1.2 on 2024-11-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0007_comment_likes_alter_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
