# Generated by Django 5.1.2 on 2024-11-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0009_comment_file_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
