# Generated by Django 5.1.2 on 2024-11-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0010_remove_comment_file_remove_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments_files/'),
        ),
    ]
